{
 "title": "ExPECA Dashboard",
 "description": "Dashboard for the ExPECA testbed at KTH",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Disk, Memory, and CPU - Aux / Storage / Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "File System Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes * 100)",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "File System Size",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_filesystem_size_bytes", "legendFormat": "{{hostname}} {{device}}" }
     ]
    },
    {
     "title": "File System Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes - node_filesystem_avail_bytes",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "File System Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2206 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes * 100)",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "CPU Load, 5 Minute Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2206 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "node_load5", "legendFormat": "{{hostname}}" }
     ]
    },
    {
     "title": "Memory Utilization, Excluding Caches and Buffers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2213 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1-(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))*100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Memory Utilization, Including Caches and Buffers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2213 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1-(node_memory_MemFree_bytes / node_memory_MemTotal_bytes))*100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Swap Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2221 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1-node_memory_SwapFree_bytes/node_memory_SwapTotal_bytes)*100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2221 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes-node_memory_SwapFree_bytes",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk, Memory, and CPU - Worker Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "File System Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes * 100)",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "File System Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_filesystem_size_bytes", "legendFormat": "{{hostname}} {{device}}" }
     ]
    },
    {
     "title": "File System Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes - node_filesystem_avail_bytes",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "File System Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (node_filesystem_avail_bytes/node_filesystem_size_bytes * 100)",
       "legendFormat": "{{hostname}} {{device}}"
      }
     ]
    },
    {
     "title": "CPU Load, 5 Minute Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "node_load5", "legendFormat": "{{hostname}}" }
     ]
    },
    {
     "title": "Memory Utilization, Excluding Caches and Buffers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1-(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))*100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Memory Utilization, Including Caches and Buffers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1-(node_memory_MemFree_bytes / node_memory_MemTotal_bytes))*100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Swap Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1-node_memory_SwapFree_bytes/node_memory_SwapTotal_bytes)*100",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes-node_memory_SwapFree_bytes",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Equipment Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Status, SDRs",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1181 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_sdr_status{sdr=~\"sdr-0[1-4]\"}[10m])"
      }
     ]
    },
    {
     "title": "Device Status, SDRs",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1181 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_sdr_status{sdr=~\"sdr-0[5-8]\"}[10m])"
      }
     ]
    },
    {
     "title": "Device Status, SDRs",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1181 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_sdr_status{sdr=~\"sdr-(0[9]|10)\"}[10m])"
      }
     ]
    },
    {
     "title": "Device Status, Worker Nodes (Ping from MGMT Router)",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1766 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_dev_status{host=~\"worker-0[1-5]-.+\"}[10m])"
      }
     ]
    },
    {
     "title": "Device Status, Worker Nodes (Ping from MGMT Router)",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1766 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_dev_status{host=~\"worker-(0[6-9]|10)-.+\"}[10m])"
      }
     ]
    },
    {
     "title": "Device Status, Advantech Routers (Ping from MGMT Router)",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1766 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_dev_status{host=~\"advantech-.+\"}[10m])"
      }
     ]
    },
    {
     "title": "Device Status, Various (Ping from MGMT Router)",
     "type": "table",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 1778 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_dev_status{host=~\"storage.+|controller.+|ptp.+\"}[10m])"
      }
     ]
    },
    {
     "title": "Device Status, Switches (Ping from MGMT Router)",
     "type": "table",
     "gridPos": { "h": 13, "w": 7, "x": 7, "y": 1778 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_dev_status{host=~\".+switch.+\"}[10m])"
      }
     ]
    },
    {
     "title": "Openstack Server Status (SSH from Controller)",
     "type": "table",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 1778 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(expeca_server_status[10m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Synchronization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "(ptp4l) PTP Offset between HW Clock and GM Clock - 6 Minute Standard Deviation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1182 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "expeca_ptp_hwstdoffset", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "(phc2sys) Offset between OS Clock and HW Clock - 6 Minute Standard Deviation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1190 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "expeca_ptp_swstdoffset", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "(ptp4l) PTP Offset between HW Clock and GM Clock - 6 Minute Maximum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1198 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "expeca_ptp_hwmaxoffset", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "(phc2sys) Offset between OS Clock and HW Clock - 6 Minute Maximum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1206 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "expeca_ptp_swmaxoffset", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "(ptp4l) PTP Offset between HW Clock and GM Clock - 6 Minute Minimum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1214 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "expeca_ptp_hwminoffset", "legendFormat": "{{host}}" }
     ]
    },
    {
     "title": "(phc2sys) Offset between OS Clock and HW Clock - 6 Minute Minimum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1222 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      { "expr": "expeca_ptp_swminoffset", "legendFormat": "{{host}}" }
     ]
    }
   ]
  },
  {
   "title": "Ericsson Private 5G",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ericsson Private 5G Throughput by IMSI - 5 Minute Average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2205 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      { "expr": "expeca_ep5g_imsi_datausage", "legendFormat": "{{imsi}} {{direction}}" }
     ]
    },
    {
     "title": "Ericsson Private 5G Throughput - 5 Minute Average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2214 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      { "expr": "expeca_ep5g_throughput", "legendFormat": "{{direction}}" }
     ]
    },
    {
     "title": "Ericsson Private 5G Watchdog Round-Trip Time - 5 Minute Average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2223 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      { "expr": "expeca_ep5g_latency", "legendFormat": "{{user}}" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server CPU Core Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(node_hwmon_temp_celsius{chip=~\"platform.*\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Server CPU Core Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max(node_hwmon_temp_celsius{chip=~\"platform.*\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Server NIC Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(node_hwmon_temp_celsius{chip=~\"0000.*\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Server NIC Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max(node_hwmon_temp_celsius{chip=~\"0000.*\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 104 },
     "options": {
      "content": "EP5G Unit Temperature Level, measured in 300s periods\n\nValues mean the following:  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 - Temperature too low, Service unavailable  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1 - Temperature very low  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2 - Temperature low  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3 - Temperature OK, slightly low  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4 - Temperature OK  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5 - Temperature OK, slightly high  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6 - Temperature high  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;7 - Temperature very high  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8 - Temperature too high, Service unavailable  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;9 - Temperature too high, Service unavailable  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unit temperature level lower than 1 or higher than 7 is an  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indication that alarm Critical Temperature Taken Out of Service  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;is imminent.  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]: Average unit temperature level 0 to 299 seconds of ROP.  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1]: Average unit temperature level 300 to 599 seconds of ROP.  \n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2]: Average unit temperature level 600 to 899 seconds of ROP.  \n\nCondition: Measurement with integration time 300sec.\n"
     }
    },
    {
     "title": "EP5G Unit Temperature Level",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"ep5gpm\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"expeca_ep5g_pm\" and r.measName == \"pmUnitTemperatureLevel\")\r\n  |> rename(columns: {_value: \"pmUnitTemperatureLevel\"})\r\n  |> group(columns: [\"index\"])  // Group by index\r\n  |> map(fn: (r) => ({ r with _field: r.index }))  // Set the series name to index\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n\r\n"
      }
     ]
    },
    {
     "title": "EP5G Unit Temperature Level",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 110 },
     "targets": [
      {
       "query": "from(bucket: \"ep5gpm\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"expeca_ep5g_pm\" and r.measName == \"pmUnitTemperatureLevel\")\r\n  |> rename(columns: {_value: \"pmUnitTemperatureLevel\"})\r\n  |> group(columns: [\"index\"])  // Group by index\r\n  |> map(fn: (r) => ({ r with _field: r.index }))  // Set the series name to index\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n\r\n"
      }
     ]
    },
    {
     "title": "EP5G SFP Module Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"ep5gpm\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"expeca_ep5g_pm\" and r.measName == \"pmSfpTemperature\")\r\n  |> rename(columns: {_value: \"pmSfpTemperature\"})\r\n  |> map(fn: (r) => ({ r with pmSfpTemperature: (float(v: r.pmSfpTemperature) - 1000.0) / 10.0 }))\r\n  |> group(columns: [\"measObjLdn\"])  // Group by measObjLdn\r\n  |> map(fn: (r) => ({ r with _field: r.measObjLdn }))  // Set the series name to measObjLdn\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n\r\n"
      }
     ]
    },
    {
     "title": "EP5G SFP Module Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"ep5gpm\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"expeca_ep5g_pm\" and r.measName == \"pmSfpTemperature\")\r\n  |> rename(columns: {_value: \"pmSfpTemperature\"})\r\n  |> map(fn: (r) => ({ r with pmSfpTemperature: (float(v: r.pmSfpTemperature) - 1000.0) / 10.0 }))\r\n  |> group(columns: [\"measObjLdn\"])  // Group by measObjLdn\r\n  |> map(fn: (r) => ({ r with _field: r.measObjLdn }))  // Set the series name to measObjLdn\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "EP5G Power Consumption Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "from(bucket: \"ep5gpm\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"expeca_ep5g_pm\" and r.measName == \"pmPowerConsumption\")\r\n  |> group(columns: [\"measObjLdn\"]) // Group by the column 'measObjLdn'\r\n  |> aggregateWindow(every: 1ns, fn: mean, column: \"_value\", createEmpty: false) // Use mean instead of sum\r\n  |> group(columns: [\"index\"]) // Group by the column 'index'\r\n  |> aggregateWindow(every: 1ns, fn: sum, column: \"_value\", createEmpty: false) // Use mean instead of sum\r\n  |> rename(columns: {_value: \"pmPowerConsumption\"})\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Openstack: Neutron",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Neutron Agent State",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2222 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_neutron_agent_state[1h])"
      }
     ]
    },
    {
     "title": "Neutron Agent of Router",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2222 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_neutron_l3_agent_of_router[1h])"
      }
     ]
    },
    {
     "title": "Neutron Network IPs Total",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2229 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_neutron_network_ip_availabilities_total[1h])"
      }
     ]
    },
    {
     "title": "Neutron Network IPs Used",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2229 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_neutron_network_ip_availabilities_used[1h])"
      }
     ]
    },
    {
     "title": "Neutron Floating IPs, Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2238 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_neutron_floating_ips" }
     ]
    },
    {
     "title": "Neutron Floating IPs, Not Active",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2238 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_neutron_floating_ips_associated_not_active"
      }
     ]
    },
    {
     "title": "Neutron Security Groups",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2238 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_neutron_security_groups"
      }
     ]
    },
    {
     "title": "Neutron Routers",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2238 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_neutron_router[1h])"
      }
     ]
    }
   ]
  },
  {
   "title": "Openstack: Cinder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cinder Limits Volume",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2223 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_cinder_limits_volume_max_gb",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Cinder Limits Volume Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2223 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(openstack_cinder_limits_volume_used_gb / openstack_cinder_limits_volume_max_gb * 100)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Cinder Limits Volume Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2223 },
     "targets": [
      {
       "expr": "(openstack_cinder_limits_volume_used_gb / openstack_cinder_limits_volume_max_gb * 100)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Cinder Pool Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2231 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "openstack_cinder_pool_capacity_total_gb",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cinder Pool Capacity Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2231 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (openstack_cinder_pool_capacity_free_gb / openstack_cinder_pool_capacity_total_gb * 100)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cinder Pool Capacity Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2231 },
     "targets": [
      {
       "expr": "100 - (openstack_cinder_pool_capacity_free_gb / openstack_cinder_pool_capacity_total_gb * 100)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cinder Volume Status",
     "type": "table",
     "gridPos": { "h": 21, "w": 12, "x": 0, "y": 2239 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_cinder_volume_status_counter[1h])"
      }
     ]
    }
   ]
  },
  {
   "title": "Openstack: Glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Glance Images",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2224 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_glance_image_bytes[1h])"
      }
     ]
    }
   ]
  },
  {
   "title": "Openstack: Identity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Identity Domains",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 2225 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_domains", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Identity Groups",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 3, "y": 2225 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_groups", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Identity Users",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 2225 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "openstack_identity_users", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Identity Project Info",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 2225 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_identity_project_info[1h])"
      }
     ]
    }
   ]
  },
  {
   "title": "Openstack: Placement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Placement Resource Total",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2226 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_placement_resource_total[1h])"
      }
     ]
    },
    {
     "title": "Placement Resource Reserved",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 2226 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_placement_resource_reserved[1h])"
      }
     ]
    },
    {
     "title": "Placement Resource Used",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 15, "y": 2226 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_placement_resource_usage[1h])"
      }
     ]
    }
   ]
  },
  {
   "title": "Service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nova agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2227 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h]))-sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h]))"
      }
     ]
    },
    {
     "title": "Nova agent status",
     "type": "table",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 2227 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h])"
      }
     ]
    },
    {
     "title": "Nova agents up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2231 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(openstack_nova_agent_state{adminState=\"enabled\"}[1h]))"
      }
     ]
    },
    {
     "title": "Cinder agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2235 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(count(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\"}[1h]))-sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\"}[1h])))"
      }
     ]
    },
    {
     "title": "Cinder agent status",
     "type": "table",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 2235 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_cinder_agent_state{adminState=\"enabled\"}[1h])"
      }
     ]
    },
    {
     "title": "Cinder agent up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2239 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(openstack_cinder_agent_state{adminState=\"enabled\"}[1h]))"
      }
     ]
    },
    {
     "title": "Neutron agents down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2243 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(last_over_time(openstack_neutron_agent_state{adminState=\"up\"}[1h]))-sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\"}[1h]))"
      }
     ]
    },
    {
     "title": "Neutron agent status",
     "type": "table",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 2243 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "last_over_time(openstack_neutron_agent_state[1h])"
      }
     ]
    },
    {
     "title": "Neutron agents up",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2247 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(openstack_neutron_agent_state{adminState=\"up\"}[1h]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall CPU cores usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2228 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(openstack_nova_vcpus_used)", "legendFormat": "used vcpu cores" },
      {
       "expr": "sum(openstack_nova_vcpus_available)",
       "legendFormat": "available vcpu cores"
      }
     ]
    },
    {
     "title": "Overall memory usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2228 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(openstack_nova_memory_used_bytes)",
       "legendFormat": "used memory"
      },
      {
       "expr": "sum(openstack_nova_memory_available_bytes)",
       "legendFormat": "available memory"
      }
     ]
    },
    {
     "title": "Keystone projects",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(openstack_identity_projects)"
      }
     ]
    },
    {
     "title": "Glance Images",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(openstack_glance_images)" }
     ]
    },
    {
     "title": "Nova instances",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(openstack_nova_total_vms)" }
     ]
    },
    {
     "title": "Associated, inactive FIPs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(openstack_neutron_floating_ips_associated_not_active)"
      }
     ]
    },
    {
     "title": "Neutron networks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(openstack_neutron_networks)"
      }
     ]
    },
    {
     "title": "Neutron subnets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(openstack_neutron_subnets)" }
     ]
    },
    {
     "title": "Cinder volumes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(openstack_cinder_volumes)" }
     ]
    },
    {
     "title": "Cinder snapshots",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2237 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(openstack_cinder_snapshots)"
      }
     ]
    }
   ]
  },
  {
   "title": "Compute nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU core usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2229 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "openstack_nova_limits_vcpus_used/(openstack_nova_limits_vcpus_max+openstack_nova_limits_vcpus_used)",
       "legendFormat": "{{tenant}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2229 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "openstack_nova_memory_used_bytes/(openstack_nova_memory_used_bytes+openstack_nova_memory_available_bytes)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Local storage usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2238 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "openstack_nova_local_storage_used_bytes/(openstack_nova_local_storage_used_bytes+openstack_nova_local_storage_available_bytes)",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume pool usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2230 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(openstack_cinder_pool_capacity_total_gb-openstack_cinder_pool_capacity_free_gb)/openstack_cinder_pool_capacity_total_gb",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Volume pool usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2230 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum(openstack_cinder_volume_gb) by (volume_type)",
       "legendFormat": "{{volume_type}}"
      }
     ]
    }
   ]
  }
 ]
}